// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RS_InputDialog","status":true,"description":"This plugin allows you to display Text Edit Box on the screen. <RS_InputDialog>","parameters":{"textBox Width":"488","textBox Height":"36","variable ID":"3","debug":"false","Text Hint":"Please enter the value...","direction":"ltr","Max Length":"255","Style":"","CSS":"\"\"","Button Name":"","Ok":"OK","Cancel":"Cancel","Position":"center"}},
{"name":"TBT_Utils","status":true,"description":"Utilities for Trial by Triage","parameters":{}},
{"name":"TBT_SentryIntegration","status":true,"description":"Connect to a remote Sentry API","parameters":{}},
{"name":"TBT_SentryOpposition","status":true,"description":"Create custom enemies from Sentry data","parameters":{}},
{"name":"TBT_CurrencySwap","status":true,"description":"Swap between ephemeral and permanent currency","parameters":{}}
];
